# TODO: Currently disabled - This workflow runs Python tests on main/develop branches,
# generates coverage reports, and uploads results to AWS S3
name: Tests

on:
  workflow_dispatch:  # Manual triggers only while disabled
  # push:
  #   branches: [ main, develop ]
  # pull_request:
  #   branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          
      - name: Run tests and generate reports
        run: |
          pytest tests/ --junitxml=test-results.xml --cov=src --cov-report=xml --cov-report=html
          
      - name: Upload test results to S3
        run: |
          aws s3 cp test-results.xml s3://${{ secrets.AWS_BUCKET }}/test-results/
          aws s3 cp coverage.xml s3://${{ secrets.AWS_BUCKET }}/coverage/
          aws s3 cp htmlcov/ s3://${{ secrets.AWS_BUCKET }}/coverage/html/ --recursive

      - name: Upload Pipeline Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-artifacts
          path: |
            test-results.xml
            coverage.xml
            htmlcov/ 